### ISSUE TITLE
update react 17

### ISSUE THREAD

**Issue by YuriFontella** [xinkule/light-toast#22]
would it be possible to upgrade to react 17 to use in projects with this version and supply this error message and not force the installation?

![image](https://user-images.githubusercontent.com/4920619/121048470-32b57100-c78d-11eb-8f6c-b1a2196e4680.png)

**Comment by xinkule** [comment]
I'll fix this soon

**Comment by xinkule** [comment]
please upgrade to 0.3.4 and try again.

**Comment by YuriFontella** [comment]
0.3.4 fixed this version issue
