### ISSUE TITLE
Toast.hide not trigger Toast ’s onTransitionEnd

### ISSUE THREAD

**Issue by githubmann** [xinkule/light-toast#8]
when i use Toast.loading and hide in request, sometime Toast's transition be trigger, but onTransitionEnd, not trigger. 
It's strange.

![image](https://user-images.githubusercontent.com/13065289/77045490-40ea6680-69fc-11ea-8b0c-99fbaa21d19f.png)
![image](https://user-images.githubusercontent.com/13065289/77045546-5c557180-69fc-11ea-8f90-3a4b0986ab16.png)

**Comment by xinkule** [comment]
Could you tell me which version you use ?

**Comment by githubmann** [comment]
0.2.3

**Comment by githubmann** [comment]
i can confirm that Toast ’s onTransitionEnd no be trigger.
that's log.
![image](https://user-images.githubusercontent.com/13065289/77047353-8e1c0780-69ff-11ea-926c-7e3a440874c9.png)

```
"react": "^16.11.0"
"react-dom": "^16.11.0"
```

**Comment by xinkule** [comment]
Can you create a minimal repo on [codesandbox](https://codesandbox.io/) to reproduce the problem ?

**Comment by githubmann** [comment]
https://9gw1d.csb.app/

https://codesandbox.io/s/musing-noyce-9gw1d

**Comment by xinkule** [comment]
Unfortunately, I couldn't reproduce in your repo, I tried both on my computer and cell phone. BTW, version 0.2.3 is aimed to resolve the issue you mentioned, I forced a reflow to make sure transition triggered. 

If you still encounter the problem time by time, I suggest you could at least wait a few moments before you hide the loading, considering it's best practice not to make the loading a flash based on user experience. And there is a [package](https://github.com/sindresorhus/p-min-delay) which can do that.

Please contact me if you have further questions.

**Comment by githubmann** [comment]
thank your explain and patience.

**Comment by xinkule** [comment]
It's my responsibility.
